src/common/components/errorTemplate/__tests__/__snapshots__/ErrorTemplate.test.tsx.snap
src/constants.ts
src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap
src/domain/app/header/__tests__/Header.test.tsx
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/i18nInit.ts
src/domain/app/i18n/sv.json
src/domain/event/formSections/priceSection/Offer.tsx
src/domain/event/formSections/priceSection/Offers.tsx
src/domain/event/formSections/responsibilitiesSection/ResponsibilitiesSection.tsx
src/domain/event/formSections/videoSection/Video.tsx
src/domain/event/formSections/videoSection/VideoSection.tsx

Remove unnecessary "Vastuuhenkilöt" headline
Swap order of "provided" and "publisher" fields
Show instruction texts for videos and prices only once
Update landing page title
Update "Give feedback" link text
Disable Swedish from UI languages
[LINK-324](https://helsinkisolutionoffice.atlassian.net/browse/LINK-324)
[LINK-325](https://helsinkisolutionoffice.atlassian.net/browse/LINK-325)
[LINK-326](https://helsinkisolutionoffice.atlassian.net/browse/LINK-326)
[LINK-328](https://helsinkisolutionoffice.atlassian.net/browse/LINK-328)
[LINK-330](https://helsinkisolutionoffice.atlassian.net/browse/LINK-330)
[LINK-332](https://helsinkisolutionoffice.atlassian.net/browse/LINK-332)

LINK-324, LINK-325, LINK-326 LINK-328, LINK-330, LINK-332 | Small improvements

---

src/domain/event/formSections/descriptionSection/DescriptionSection.tsx

Use full container width for the description
[LINK-553](https://helsinkisolutionoffice.atlassian.net/browse/LINK-553)

LINK-553 | Wider width for the description field

---

.github/workflows/production.yml
.github/workflows/production_scheduled_tests.yml
.github/workflows/review.yml
.github/workflows/staging.yml
.github/workflows/staging_scheduled_tests.yml

Fix GitHub Actions deprecations warnings by updating following actions:
- actions/cache@v2 -> actions/cache@v3
- actions/checkout@v2 -> actions/checkout@v3
- actions/setup-node@v2.1.2 -> actions/setup-node@v3
- actions/upload-artifact@v2->actions/upload-artifact@v3
[LINK-1157](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1157)
[LINK-1157]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
You can see latest GitHub action run at https://github.com/City-of-Helsinki/linkedcomponents-ui/actions/runs/4162129527

LINK-1157 | Update GitHub actions to latest versions to fix deprecation warnings

---

src/common/components/imageUploader/imageDropzone/ImageDropzone.tsx
src/constants.ts
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/image/__tests__/CreateImagePage.test.tsx

Backend max file name length will be increased to 255. However, during processing, the filename will increase in length. BE will add prefix folder path to the file name that gets stored in the DB and also a unique suffix identifier if the file name already exists. So we leave 55 characters as wiggle room.
https://helsinkisolutionoffice.atlassian.net/browse/LINK-991

Limit file name length to 200 characters

---

src/common/components/keywordSelector/KeywordSelector.tsx
src/common/components/keywordSelector/__mocks__/keywordSelector.ts
src/domain/event/formSections/classificationSection/__mocks__/classificationSection.ts

free_text uses trigram similarity to filter and sort results. This is 50% slower, but allows for more accurate results with exact matches automatically ranked on top.
[LINK-1242](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1242)
[LINK-1242]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use free_text in KeywordSelector

---

src/domain/app/header/header.module.scss

Increase header z-index to prevent map to hide header
[LINK-1244](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1244)
Fix can be tested locally at http://localhost:3000/fi/administration/places/create
[LINK-1244]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1244 | Increase header z-index to prevent map to hide header

---

src/common/components/imagePreview/ImagePreview.tsx
src/common/components/imageSelector/ImageSelector.tsx
src/common/components/imageSelector/__mocks__/imageSelector.ts
src/common/components/imageSelector/__tests__/ImageSelector.test.tsx
src/common/components/imageSelector/imageSelector.module.scss
src/constants.ts
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/formSections/imageSection/__mocks__/imageSection.ts
src/domain/images/constants.ts
src/domain/images/imagesTable/ImagesTable.tsx
src/hooks/__tests__/useShowPlaceholderImage.test.ts
src/hooks/useShowPlaceholderImage.ts

- Support filtering image table by id and name columns
- Support filtering images by name and alt text in image selector component
- Show placeholder image is image in the url is not available
[LINK-130](https://helsinkisolutionoffice.atlassian.net/browse/LINK-130)
[LINK-348](https://helsinkisolutionoffice.atlassian.net/browse/LINK-348)
Testing image filtering when adding image to an event:
1. Open http://localhost:3000/fi/events/create
2. Click "Lisää tapahtuman kuva"
Sorting image table can be tested at http://localhost:3000/fi/administration/images
[LINK-130]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LINK-348]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-348?atl …

LINK-130, LINK-348 | Support filtering images by text

---

schema.js
src/domain/organization/__mocks__/createOrganizationPage.ts
src/domain/organization/__mocks__/editOrganizationPage.ts
src/domain/organization/__tests__/utils.test.ts
src/domain/organization/utils.ts
src/generated/graphql.tsx

Send user ids in correct form when saving organisation users
[LINK-1053](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1053)
[LINK-1054](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1054)
[LINK-1053]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LINK-1054]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1053, LINK-1054 | Saving organisation users

---

src/constants.ts
src/domain/app/footer/Footer.tsx
src/domain/app/footer/__tests__/Footer.test.tsx
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json

Add data protection link to footer items.
**[LINK-1173](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1173):**
[LINK-1173]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1773 | Footer add data protection item

---

src/common/components/formFields/hooks/__tests__/useMultiSelectFieldProps.test.tsx
src/common/components/formFields/hooks/__tests__/useSingleSelectFieldProps.test.tsx
src/common/components/formFields/hooks/useMultiSelectFieldProps.ts
src/common/components/formFields/hooks/useSingleSelectFieldProps.ts
src/common/components/formFields/keywordSelectorField/KeywordSelectorField.tsx
src/common/components/formFields/placeSelectorField/PlaceSelectorField.tsx
src/common/components/formFields/publisherSelectorField/PublisherSelectorField.tsx
src/common/components/formFields/registrationEventSelectorField/RegistrationEventSelectorField.tsx
src/common/components/formFields/singleKeywordSelectorField/SingleKeywordSelectorField.tsx
src/common/components/formFields/singleOrganizationClassSelectorField/SingleOrganizationClassSelectorField.tsx
src/common/components/formFields/singleOrganizationSelectorField/SingleOrganizationSelectorField.tsx
src/common/components/formFields/singleSelectField/SingleSelectField.tsx
src/common/components/formFields/umbrellaEventSelectorField/UmbrellaEventSelectorField.tsx
src/common/components/formFields/userSelectorField/UserSelectorField.tsx

At the moment user can remove combobox value event if component is disabled. You can reproduce this in publisher field at https://linkedcomponents-ui-dev.agw.arodevtest.hel.fi/fi/administration/keyword-sets/edit/ahjo:testq?returnPath=%2Fadministration%2Fkeyword-sets
Purpose of this PR is to prevent onChange when component is disabled
[LINK-1272](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1272)
[LINK-1272]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1272 | Don't allow to delete combobox value when component is disabled

---

src/constants.ts
src/domain/app/footer/Footer.tsx
src/domain/app/footer/__tests__/Footer.test.tsx

Change footer data protection item to localised links (english version doesn't exist, so uses finnish)
**[LINK-1173](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1173):**
[LINK-1173]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1773 Footer data protection item localised links

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/constants.tsx
src/domain/event/utils.ts
src/domain/events/eventActionsDropdown/EventActionsDropdown.tsx
src/domain/events/eventActionsDropdown/__tests__/EventActionsDropdown.test.tsx

Send Email button to send notification information to event creator in the event listing page.
The email information has to be parsed from the createdBy string which usually contains email address. There is potential that if the createdBy field is malformed that this feature does not work.
**[LINK-1266](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1266):**
[LINK-1266]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added Email button for the event list page

---

src/domain/app/authenticationNotification/AuthenticationNotification.tsx
src/domain/app/authenticationNotification/__tests__/AuthenticationNotification.test.tsx
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/constants.tsx
src/domain/event/eventAuthenticationNotification/EventAuthenticationNotification.tsx
src/domain/event/formSections/descriptionSection/DescriptionSection.tsx
src/domain/event/formSections/languagesSection/LanguagesSection.tsx
src/domain/event/formSections/typeSection/TypeSection.tsx
src/domain/event/formSections/typeSection/publicationListLinks/PublicationListLinks.module.scss
src/domain/event/formSections/typeSection/publicationListLinks/PublicationListLinks.tsx

Changes to event form info texts, which are required after https://github.com/City-of-Helsinki/linkedcomponents-ui/pull/185 external users are enabled for Linked events.
**NOTE:**
https://github.com/City-of-Helsinki/linkedcomponents-ui/pull/185 should be merged first, these changes are not relevant without it.
**[LINK-1342](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1342):**
Tested on local machine
[LINK-1342]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1342 event form info texts update

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/enrolment/CreateEnrolmentPage.tsx
src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx
src/domain/enrolment/enrolmentForm/availableSeatsText/AvailableSeatsText.tsx
src/domain/enrolment/enrolmentForm/availableSeatsText/__tests__/AvailableSeatsText.test.tsx
src/domain/enrolment/participantAmountSelector/__tests__/ParticipantAmountSelector.test.tsx
src/domain/enrolment/registrationWarning/RegistrationWarning.tsx
src/domain/enrolment/registrationWarning/__tests__/RegistrationWarning.test.tsx
src/domain/enrolment/reservationTimer/__tests__/ReservationTimer.test.tsx
src/domain/events/eventActionsDropdown/EventActionsDropdown.tsx
src/domain/registration/__mocks__/registration.ts
src/domain/registration/__tests__/utils.test.ts
src/domain/registration/utils.ts
src/utils/mockDataUtils.ts

- Enrolment is closed if enrolment_start_time is defined and is in the future or enrolment_end_time is defined and is in the past
- Show different warning message if enrolment is open but there is no available seats
- Add reserved seats to available seats amount if there is already reservation in the session storage
- Disable enrolment form also if there is no available places and seats reservation is not stored to session storage
PR for API implementation: https://github.com/City-of-Helsinki/linkedevents/pull/611
[LINK-1363](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1363)
[LINK-1363]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1363 | Prevent to reserve seats or signup is enrolment is not open

---

schema.js
src/domain/event/__tests__/EditEventPage.test.tsx
src/domain/organization/__mocks__/createOrganizationPage.ts
src/domain/organization/__mocks__/editOrganizationPage.ts
src/domain/organization/__tests__/utils.test.ts
src/domain/organization/utils.ts
src/generated/graphql.tsx

Use format 
´´´
{
"admin_users": [ "u-ui745qfmxmi63dvsbjmavaacea" ],
"regular_users": [ "u-ui745qfmxmi63dvsbjmavaacea" ],
...
}
´´´
instead of
´´´
{
"admin_users": { "username": [ "u-ui745qfmxmi63dvsbjmavaacea" ] },
"regular_users": { "username": [ "u-ui745qfmxmi63dvsbjmavaacea" ] },
...
}
´´´
NOTE: https://github.com/City-of-Helsinki/linkedevents/pull/609 should be merged before this
[LINK-1374](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1374)
[LINK-1374]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1374 | Unify format of saving organization users with API

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/formSections/placeSection/PlaceSection.tsx

Add more information about the venue inside/outside to the info text.
Add more information about the venue inside/outside selection to the notification info text.
Part of:
**[LINK-1034](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1034)**
The addition is highlighted selecting with the cursor in the below image.
[LINK-1034]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1034/add-venue-inside-outside-text.

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/eventForm/EventForm.tsx
src/domain/event/formSections/eventStateInfoSection/EventStateInfoSection.tsx
src/domain/event/formSections/eventStateInfoSection/eventStateInfoSection.module.scss

This PR adds an informative text to event form page, that Draft will be published/cancelled by moderators.
[LINK-1380](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1380)
[LINK-1380]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Link 1380 | Add information that Draft will be published/cancelled by moderators

---

src/domain/events/__mocks__/eventsPage.ts
src/domain/events/eventList/EventList.tsx
src/domain/events/utils.ts

Add `start: 'now'` as default to `waitingApprovalVariables` and change the order of
combining variables in `EventList` because `getEventsQueryVariables`'s result contains `start: null` which would overwrite `baseVariables`'s start value.
**[LINK-110](https://helsinkisolutionoffice.atlassian.net/browse/LINK-110):**
- Tested on local machine
[LINK-110]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-110 - add start: 'now' as default to

---

src/domain/enrolment/__mocks__/createEnrolmentPage.ts
src/domain/enrolment/__mocks__/editEnrolmentPage.ts
src/domain/enrolment/__tests__/CreateEnrolmentPage.test.tsx
src/domain/enrolment/__tests__/EditEnrolmentPage.test.tsx
src/domain/enrolment/__tests__/utils.test.ts
src/domain/enrolment/__tests__/validation.test.ts
src/domain/enrolment/constants.tsx
src/domain/enrolment/enrolmentFormFields/EnrolmentFormFields.tsx
src/domain/enrolment/utils.ts

Allow only select email as notification type in enrolment
[LINK-1366](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1366)
[LINK-1366]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1366 | Allow only select email as notification type in enrolment

---

.env
README.md
package.json
yarn.lock

- https://sentry.test.hel.ninja/ and https://sentry.hel.fi/ supports latest Sentry version so upgrade @sentry/react to version 7.57.0
- Also remove REACT_APP_SENTRY_DSN default value and update README.md
[LINK-1364](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1364)
[LINK-1364]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1364 | Upgrade @sentry/react to version 7.57.0

---

README.md
src/domain/app/layout/pageLayout/PageLayout.tsx
src/domain/app/layout/pageLayout/pageLayout.module.scss

`grid-template-rows: auto 1fr auto;` in `.pageLayout` css class breaks page layout when REACT_APP_MAINTENANCE_SHOW_NOTIFICATION is enabled. Change it to `grid-template-rows: auto auto 1fr auto;` in that case.
Document REACT_APP_MAINTENANCE_SHOW_NOTIFICATION and REACT_APP_MAINTENANCE_DISABLE_LOGIN in README.me
Page layout before change:
Page layout after change:

Fix page layout when maintenance notification is enabled

---

src/domain/enrolment/enrolmentFormFields/EnrolmentFormFields.tsx
src/domain/enrolment/hooks/useLanguageOptions.ts
src/domain/event/formSections/languagesSection/LanguagesSection.tsx
src/domain/language/utils.ts
src/domain/registration/formSections/registrationUserAccessesSection/registrationUserAccess/RegistrationUserAccess.tsx

API is expecting to get @id value when defining in_language for the event. Before this commit UI sent id instead.
[LINK-1473](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1473)
PR fixes this problem:
[LINK-1473]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1473 | Use @id instead of id when defining in_language for the event

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json

Add missing SV translations + minor FI and EN translation fixes.
**[LINK-1342](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1342):**
[LINK-1342]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1342 add missing translations

---

src/domain/event/__tests__/utils.test.ts
src/domain/event/utils.ts

This PR fixes problem with creating new registration when coping values from a published event.
**Steps to reproduce the bug:**
1. Open a published event without a registration
2. Click add “Registration for event“ button 
3. Enter enrolment start and end dates 
4. Click Save button
**End result:** 
UI shows Event: Epäkelpo linkki - URL ei täsmää. -error
Use event @id instead of id when coping event values to registration form to fix this issue.
[LINK-1475](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1475)
Screenshot of the fixed server error message.
[LINK-1475]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use event @id instead of id when coping event values to registration form

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json

Change date to maintenance warning
**[LINK-1445](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1445):**
[LINK-1445]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1445 New date to maintenance warning

---

src/domain/app/cookieConsent/CookieConsent.tsx

Define domain for the cookie consent modal cookies. Reason for this is that https://www.hel.fi/fi clear all the cookies that it's not using. So visiting in that site also cleared cookies from Linked Registration UI
[LINK-1482](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1482)
[LINK-1482]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1482 | Define domain for the cookie consent modal cookies

---

src/domain/signupGroup/hooks/useNotificationOptions.ts

Hide SMS notification options since it's not supported in API
[LINK-1505](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1505)
[LINK-1505]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1505 | Hide SMS notification options since it's not supported in API

---

src/domain/signup/__tests__/EditSignupPage.test.tsx
src/domain/signupGroup/__tests__/EditSignupGroupPage.test.tsx
src/domain/signupGroup/signupGroupForm/SignupGroupForm.tsx
src/domain/signupGroup/signupGroupFormFields/SignupGroupFormFields.tsx

Hide signup group extra info field when editing a signup
[LINK-1613](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1613)
[LINK-1613]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1613 | Hide signup group extra info field when editing a signup

---

src/domain/signup/EditSignupPage.tsx
src/domain/signup/editSignupButtonPanel/__tests__/EditSignupButtonPanel.test.tsx
src/domain/signupGroup/CreateSignupGroupPage.tsx
src/domain/signupGroup/EditSignupGroupPage.tsx
src/domain/signupGroup/__tests__/CreateSignupGroupPage.test.tsx
src/domain/signupGroup/participantAmountSelector/ParticipantAmountSelector.tsx
src/domain/signupGroup/participantAmountSelector/__tests__/ParticipantAmountSelector.test.tsx
src/domain/signupGroup/reservationTimer/__tests__/ReservationTimer.test.tsx
src/domain/signupGroup/signupGroupFormContext/SignupGroupFormContext.tsx
src/domain/signupGroup/signupGroupFormFields/signups/Signups.tsx
src/domain/signups/SignupsPage.tsx
src/domain/signups/signupActionsDropdown/__tests__/SignupActionsDropdown.test.tsx
src/domain/signups/signupsTable/__tests__/SignupsTable.test.tsx

Move participant amount value to SignupGroupFormContext and update it after deleting a signup from the form
[LINK-1619](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1619)
1. Open create signup group page
2. Input at least 2 to the participant amount input and press update button
3. Delete one of the signups
Expected result:
Participant amount input value should be updated to match number of signups in the form
[LINK-1619]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1619 | Update participant amount input value after deleting a signup

---

src/domain/event/__tests__/EditEventPage.test.tsx
src/domain/event/eventForm/EventForm.tsx
src/domain/event/formSections/externalUserContact/ExternalUserContact.tsx
src/domain/organization/utils.ts

Moderator should be able to see external users contact information when previewing on edit page. However this information should not be edited, so keeping the fields disabled.
**[LINK-1563](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1563):**
[LINK-1563]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1563 moderator sees external user contact info

---

src/common/components/table/clickableRow.module.scss
src/common/components/table/table.module.scss
src/domain/events/eventsTable/eventsTable.module.scss
src/domain/organizations/organizationsTable/organizationsTable.module.scss

Separate file for table clickableRow to avoid import issues
This PR should fix issues when parsing stylesheets at https://linkedevents.dev.hel.ninja/fi/events.
Original issue can be produced:
1. Build project with `yarn build`
2. Preview builded project with `yarn serve`
3. Open http://localhost:3000/en/events by using Safari or Firefox
-> Blank screen with `Did not parse stylesheet at...` errors

Separate file for table clickableRow to avoid import issues

---

schema.js
src/domain/signups/__mocks__/signupsPage.ts
src/domain/signups/__tests__/utils.test.ts
src/domain/signups/query.ts
src/domain/signups/signupsTable/SignupsTable.tsx
src/domain/signups/signupsTable/__tests__/SignupsTable.test.tsx
src/domain/signups/utils.ts
src/generated/graphql.tsx

At the moment signups table is using client side pagination. However signups endpoint response is already paginated and with current implementation use can see only the first page of the data and some signups are missing
[LINK-1673](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1673)
[LINK-1673]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1673 | Replace client side pagination with server side pagination

---

src/domain/event/__mocks__/editEventPage.ts
src/domain/event/__tests__/EditEventPage.test.tsx
src/domain/event/eventForm/EventForm.tsx
src/domain/events/eventsTable/eventsTableRow/EventsTableRow.tsx
src/domain/events/eventsTable/eventsTableRow/__tests__/EventsTableRow.test.tsx
src/domain/organization/__mocks__/organization.ts
src/domain/user/__mocks__/user.ts

See LINK-1697 - contact information needs to be shown admins only when the event is external.

Hide contact information from admins if the event is not external

---

src/domain/registrations/registrationsTable/RegistrationsTable.tsx
src/domain/registrations/registrationsTable/__tests__/RegistrationsTable.test.tsx
src/domain/signups/signupsTable/SignupsTable.tsx
src/domain/signups/signupsTable/__tests__/SignupsTable.test.tsx
src/domain/signups/signupsTable/signupsTable.module.scss

Display signup name as a link in signups table
Display event name as a link in registrations table
[LINK-1688](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1688)
[LINK-1688]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1688 | Display signup and registration name as a link

---

azure-pipelines-acceptance-tests.yml
azure-pipelines-build-devtest.yml
azure-pipelines-build-staging.yml
azure-pipelines-e2e-dev.yml
azure-pipelines-e2e-prod.yml

`develop` branch was renamed to `main`. Need to change pipelines to use `main` instead of `develop` as well.
**[LINK-1709](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1709)**
[LINK-1709]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1709: Rename develop branch to main

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/registration/__tests__/utils.test.ts
src/domain/registration/editButtonPanel/EditButtonPanel.tsx
src/domain/registration/editButtonPanel/__tests__/EditButtonPanel.test.tsx
src/domain/registration/utils.ts
src/domain/registrations/constants.tsx
src/domain/registrations/registrationActionsDropdown/RegistrationActionsDropdown.tsx
src/domain/registrations/registrationActionsDropdown/__tests__/RegistrationActionsDropdown.test.tsx
src/domain/signups/SignupsPage.tsx
src/domain/signups/__tests__/SignupsPage.test.tsx
src/domain/signups/__tests__/testUtils.ts
src/utils/__tests__/stripTrailingSlash.ts
src/utils/stripTrailingSlash.ts

Support exporting registration signups as an Excel file
Allow users to export signups in registration list page, registration edit page and signups page
[LINK-1661](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1661)
[LINK-1661]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1661 | Export signups as Excel file

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/signupGroup/signupGroupFormFields/SignupGroupFormFields.tsx
src/domain/signupGroup/signupGroupFormFields/signups/signup/Signup.tsx

Add helper text for signup extra info field and notification for contact person section
Update user consent text
[LINK-1715](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1715)
[LINK-1715]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1715 | Info texts to signup form

---

src/domain/help/pages/termsOfUsePage/TermsOfUsePage.tsx

Fix heading levels on Terms on use page
[LINK-1771](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1771)
[LINK-1771]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1771 | Fix heading levels on Terms on use page

---

src/domain/feedback/successNotification/SuccessNotification.tsx
src/domain/feedback/successNotification/successNotification.module.scss
src/domain/help/pages/askPermissionPage/AskPermissionPage.tsx
src/domain/help/pages/askPermissionPage/__tests__/AskPermissionPage.test.tsx
src/domain/help/pages/contactPage/ContactPage.tsx
src/domain/help/pages/contactPage/__tests__/ContactPage.test.tsx
src/domain/help/pages/testUtils.ts

Focus to notification heading after successful ask permission or contact form submit to give screen readers feedback that the submit succeeded.
[LINK-1772](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1772)
[LINK-1773](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1773)
[LINK-1772]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LINK-1773]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1772, LINK-1773 | Focus to notification heading after contact form submit

---

README.md

New django-heluser library requires that the client for logging into Django admin has a non-url client id.

LINK-1790 | Update instructions for creating working Tunnistamo clients

---

src/domain/auth/constants.ts

email scope was missing from original [PR](https://github.com/City-of-Helsinki/linkedcomponents-ui/pull/303) which implemented new login feature Jira: [LINK-1700](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1700) and [LINK-1774](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1774) . 
This probably makes possible to fix content management rights problems mentioned in comments of [LINK-1700](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1700), but this doesn't fix AD logout problem.
[LINK-1700]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LINK-1774]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …

LINK-1700 Add email to the scope of user manager settings

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json

On Events page should use same translation for navigation and breadcrumbs.
**[LINK-1749](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1749):**
[LINK-1749]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: events, same translations for navigation and breadcrumbs LINK-1749

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/registration/__tests__/utils.test.ts
src/domain/registration/utils.ts

Display enrolment start time when registration is closed
[LINK-1820](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1820)
[LINK-1820]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1820 | Display enrolment start time when registration is closed

---

src/domain/auth/hooks/useAuth.ts

Add ui_locales parameter to Keycloak url so the selected language is used also in the authentication service

fix: use selected language in login

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/signups/__tests__/utils.test.ts
src/domain/signups/signupsTable/SignupsTable.tsx
src/domain/signups/signupsTable/__tests__/SignupsTable.test.tsx
src/domain/signups/types.ts
src/domain/signups/utils.ts

At the moment signups table displays only contact person's email and phone number. Add also signup's phone number to the table and rename columns of contact person's email and phone number
[LINK-1862](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1862)
[LINK-1862]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add signup phone number to table

---

src/domain/app/footer/Footer.tsx
src/domain/app/footer/__tests__/Footer.test.tsx
src/domain/app/footer/constants.ts
src/domain/app/i18n/en.json

As of now, Linked events does not have a search functionality for navigating pages. Adding 
sitemap / link list to the footer.
**[LINK-1746](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1746):**
[LINK-1746]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1746 a11y footer link list

---

src/domain/app/layout/titleRow/TitleRow.tsx
src/domain/app/routes/helpPageRoutes/__tests__/HelpPageRoutes.test.tsx
src/domain/eventSearch/searchPanel/SearchPanel.tsx
src/domain/eventSearch/searchPanel/searchPanel.module.scss
src/domain/help/pages/apiPage/ApiPage.tsx
src/domain/help/pages/askPermissionPage/AskPermissionPage.tsx
src/domain/help/pages/contactPage/ContactPage.tsx
src/domain/help/pages/controlPanelPage/ControlPanelPage.tsx
src/domain/help/pages/documentationPage/DocumentationPage.tsx
src/domain/help/pages/faqPage/FaqPage.tsx
src/domain/help/pages/featuresPage/FeaturesPage.tsx
src/domain/help/pages/generalInstructionsPage/GeneralInstructionsPage.tsx
src/domain/help/pages/generalTechologyPage/GeneralTechnologyPage.tsx
src/domain/help/pages/imageRightsPage/ImageRightsPage.tsx
src/domain/help/pages/platformPage/PlatformPage.tsx
src/domain/help/pages/registrationInstructions/RegistrationInstructions.tsx
src/domain/help/pages/sourceCodePage/SourceCodePage.tsx
src/domain/help/pages/termsOfUsePage/TermsOfUsePage.tsx

Adding breadcrumbs on search and support pages.
**[LINK-1747](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1747):**
[LINK-1747]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: search events and support pages, add breadcrumbs LINK-1747

---

browser-tests/eventSearch/eventSearch.components.ts
browser-tests/footer/footer.components.ts
browser-tests/footer/footer.testcafe.ts
browser-tests/header/header.components.ts
browser-tests/header/header.testcafe.ts
browser-tests/help/help.testcafe.ts
browser-tests/landingPage/landingPage.testcafe.ts
browser-tests/utils/url.utils.ts
package.json
src/domain/signupGroup/signupGroupFormFields/signups/signup/__test__/Signup.test.tsx
yarn.lock

Fix failing test by is caused by the missing prop in the test file.
Fix failing e2e tests.
Add e2e tests for the footer links which still are missing tests
[LINK-1891](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1891)
[LINK-1891]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1891 | Fix failing tests

---

src/domain/language/hooks/__tests__/useLanguageOptions.test.tsx
src/domain/language/hooks/useLanguageOptions.ts
src/domain/language/utils.ts

Prioritise most used languages in the Native language and Service language dropdown in the signup form
[LINK-1848](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1848)
[LINK-1848]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1848 | prioritise most used language options

---

src/domain/app/App.tsx
src/domain/app/routes/adminRoutes/AdminRoutes.tsx
src/domain/app/routes/helpPageRoutes/HelpPageRoutes.tsx
src/domain/app/routes/localeRoutes/LocaleRoutes.tsx
src/domain/app/routes/registrationRoutes/RegistrationRoutes.tsx
src/domain/attendanceList/AttendanceListPage.tsx
src/domain/event/EditEventPage.tsx
src/domain/image/EditImagePage.tsx
src/domain/keyword/EditKeywordPage.tsx
src/domain/keywordSet/EditKeywordSetPage.tsx
src/domain/notFound/NotFound.tsx
src/domain/organization/EditOrganizationPage.tsx
src/domain/place/EditPlacePage.tsx
src/domain/registration/EditRegistrationPage.tsx
src/domain/signup/EditSignupPage.tsx
src/domain/signupGroup/CreateSignupGroupPage.tsx
src/domain/signupGroup/EditSignupGroupPage.tsx
src/domain/signups/SignupsPage.tsx

- At the moment unauthenticated user is redirected to the landing page after logging in from registration or admin pages. Change this behaviour so that the same url is opened after logging in.
- Always refresh api tokens in the first render if user is already authenticated to avoid using expired api tokens.
[LINK-1900](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1900)
[LINK-1900]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1900 | Fine-tune authentication

---

src/common/components/formFields/hooks/__tests__/useMultiSelectFieldProps.test.tsx
src/common/components/formFields/hooks/__tests__/useSingleSelectFieldProps.test.tsx
src/common/components/formFields/hooks/useMultiSelectFieldProps.ts
src/common/components/formFields/hooks/useSingleSelectFieldProps.ts
src/domain/registration/formSections/priceGroups/__tests__/PriceGroupSection.test.tsx

- Android devices freezes totally when trying to change value of a SingleSelectComponent. Add a short timeout to prevent infinite loop after calling onChange.
[LINK-1936](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1936)
[LINK-1936]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1936 | Add timeout to SingleSelectComponent value change

---

src/common/components/highlight/Highlight.tsx
src/common/components/highlight/highlight.module.scss
src/domain/help/pages/platformPage/PlatformPage.tsx
src/domain/landingPage/LandingPage.tsx
src/domain/landingPage/__tests__/LangingPage.test.tsx

The grouping of the different plots was not clear to the screen reader. This was fixed by wrapping highlight component with section tag and by adding role="heading" for the title
[LINK-1758](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1758)
[LINK-1758]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1758 | improve accessibility of highlight component

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json

Rename "Siirry hallintasivulle" button as "Hallintatyökalut"
[LINK-1768](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1768)
[LINK-1768]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Rename admin section navigation button

---

src/domain/event/eventPage.module.scss
src/domain/event/formSections/priceSection/PriceSection.tsx
src/domain/event/formSections/priceSection/__tests__/PriceSection.test.tsx
src/domain/event/formSections/priceSection/offers/offer/Offer.tsx
src/domain/event/formSections/priceSection/priceNotification/PriceNotification.tsx

Display notification for each offer
Swap description and info url fields order
[LINK-1908](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1908)
[LINK-1908]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1908 | Offer usability improvements

---

src/common/components/formFields/checkboxGroupField/CheckboxGroupField.tsx
src/common/components/formFields/checkboxGroupField/__tests__/CheckboxGroupField.test.tsx
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/formSections/audienceSection/AudienceSection.tsx
src/domain/event/formSections/audienceSection/__tests__/AudienceSection.test.tsx
src/domain/event/formSections/classificationSection/ClassificationSection.tsx
src/domain/event/formSections/classificationSection/__tests__/ClassificationSection.test.tsx
src/domain/event/formSections/languagesSection/LanguagesSection.tsx

- Display accessibility notification after showing more or hiding options in checkbox group
- Display all the options in main categories, topics and languages checkbox group
[LINK-1761](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1761)
[LINK-1761]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1761 | Improve accessibility of checkbox group

---

src/domain/events/eventsTable/EventsTable.tsx

Start and end time column headers are in incorrect order. fix the order in this PR
[LINK-1949](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1949)
[LINK-1949]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1949 | Change column header order in events table

---

src/domain/event/formSections/descriptionSection/DescriptionSection.tsx

Move event description field to be immediately after short description field
[LINK-1953](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1953)
[LINK-1953]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1953 | move event description field location in event form

---

src/domain/event/formSections/descriptionSection/DescriptionSection.tsx

Change short description field type to textarea in event form
[LINK-1955](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1955)
[LINK-1955]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1955 | Change short description field type

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json

Fine-tune external user instruction text
[LINK-1951](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1951)
[LINK-1951]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1951 | Fine-tune external user instruction text

---

e2e/tests/help.spec.ts
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json

Rename support page navigation
[LINK-1983](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1983)
[LINK-1983]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1983 | Rename support page navigation

---

src/common/components/imageSelector/__mocks__/imageSelector.ts
src/common/components/imageSelector/__tests__/ImageSelector.test.tsx
src/common/components/table/__tests__/Table.test.tsx
src/common/components/timeInput/__tests__/TimeInput.test.tsx
src/domain/app/routes/localeRoutes/__tests__/LocaleRoutes.test.tsx
src/domain/event/__tests__/CreateEventPage.test.tsx
src/domain/event/__tests__/EditEventPage.test.tsx
src/domain/event/formSections/imageSection/__mocks__/imageSection.ts
src/domain/event/formSections/imageSection/__tests__/ImageSection.test.tsx
src/domain/eventSaved/__tests__/EventSavedPage.test.tsx
src/domain/priceGroup/__mocks__/priceGroups.ts

LocaleRoutes: 
- Use test specific mocks instead of having common mocks variable which contains all the mocks 
- Add missing mocks to get rid of some warnings
CreateEventPage:
- Add missing mocks to get rid of some warnings
EditEventPage:
- Add missing mocks to get rid of some warnings 
mock HTMLCanvasElement.prototype.getContext function to solve accessibility test warnings
Note that there still are some warnings caused by the same name (Tuki - Tuki) in help page breadcrumbs. This issue will be solved in the LINK-1770 and can be ignored here.
[LINK-1966](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1966)
[LINK-1966]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1966 | fix vitest warnings

---

e2e/tests/events.spec.ts

The purpose for the original query is to test that 0 results is found. Current query matches also if amount of events ends with 0. e.g. 10280 tapahtumaa. Add exact parameter to avoid the issue.

fix: require exact match in event search test

---

src/common/components/textEditor/ckeditor.scss
src/common/components/timeInput/customTimeInput.module.scss

Unify text editor and time input components disabled styles with other input components
[LINK-2004](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2004)
[LINK-2004]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2004 | fine-tune input components disabled styles

---

e2e/tests/help.spec.ts
e2e/tests/landing.spec.ts

- Fix for an unreliable "contact form" test
- Cookie consent dialog test removed from e2e suite as it is covered by unit tests
run `yarn run test:e2e` locally.

test: fix for contact form test

---

src/common/components/textArea/TextArea.tsx
src/common/components/textArea/__tests__/__snapshots__/TextArea.test.tsx.snap
src/common/components/textArea/textArea.module.scss
src/common/components/textEditor/textEditor.module.scss

Prevent to resize text area fields
Make text editor field height to match with description instructions notification
[LINK-2027](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2027)
[LINK-2027]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2027 | fine-tune styles of description fields

---

.env.local.example
.gitignore
e2e/tests/api.spec.ts
e2e/tests/create.spec.ts
e2e/tests/events.spec.ts
e2e/tests/help.spec.ts
e2e/tests/landing.spec.ts
e2e/tests/utils.ts
playwright.config.ts

- E2E tests for "Create event" feature
- API tests
This PR implements these tests with Playwright: https://helsinkisolutionoffice.atlassian.net/wiki/spaces/KAN/pages/8240922654/Linked+Events+-+Test+Cases+Q2+2023
run `yarn test:e2e` locally.

test: create event and api tests

---

src/common/components/buttonPanel/buttonPanel.module.scss

There is a issue when navigating pages with ButtonPanel on Windows & Chrome + NVDA combination where focus can get stuck underneath sticky positioned ButtonPanel. Removing sticky positioning will make sure this cannot happen.
**[LINK-1751](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1751):**
[LINK-1751]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: a11y make ButtonPanel not sticky LINK-1751

---

src/domain/signup/__tests__/permissions.test.ts
src/domain/signup/editSignupButtonPanel/EditSignupButtonPanel.tsx
src/domain/signup/permissions.ts
src/domain/signupGroup/__tests__/permissions.test.ts
src/domain/signupGroup/permissions.ts
src/domain/signups/signupActionsDropdown/SignupActionsDropdown.tsx
src/domain/signups/signupsTable/SignupsTable.tsx

Don't allow to delete signup group if it has at least 1 signup which has a payment cancellation or refund
Don't allow to delete signup if it's part of signup group which has a payment cancellation or refund
[LINK-2089](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2089)
[LINK-2089]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2089 | Prevent to delete signup or signup group with payment cancellation/refund

---

src/domain/app/sentry/__tests__/utils.test.ts
src/domain/app/sentry/utils.ts
src/hooks/useHandleError.ts
src/index.tsx
vite.config.ts

Adds `beforeSend` and `beforeSendTransaction` functions to Sentry client to scrub sensitive information before it is sent to the Sentry server.
[LINK-2030](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2030)
[LINK-2030]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2030 | scrub sensitive data from Sentry requests

---

.gitignore
src/domain/signupGroup/validation.ts

**[LINK-2178](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2178):**
Tested with event that has no age limits and with event that does.
- make a new event + registration
- add participant via linkedevents
Can use this:
https://linkedevents.dev.hel.ninja/en/registrations/224/signup-group/create?text=jep&returnPath=%2Fregistrations&returnPath=%2Fregistrations%2F224%2Fsignups
and this: 
https://linkedevents.dev.hel.ninja/en/registrations/226/signup-group/create?text=jep&returnPath=%2Fregistrations&returnPath=%2Fregistrations%2F226%2Fsignups
With the bug this submit button does nothing.  When fixed it works.
[LINK-2178]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: submit registration does nothing LINK-2178

---

package.json
yarn.lock

Bump `micromatch` version to 4.0.8. No new version available for `@graphql-codegen`, so keeping it in resolutions. This fixes medium vulnerability:
- https://github.com/City-of-Helsinki/linkedcomponents-ui/security/dependabot/139
**[LINK-2191](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2191):**
[LINK-2191]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

deps: bump micromatch to 4.0.8 LINK-2191

---

package.json
src/common/components/textEditor/__tests__/TextEditor.test.tsx
src/domain/event/__tests__/CreateEventPage.test.tsx
src/domain/event/formSections/descriptionSection/__tests__/DescriptionSection.test.tsx
src/domain/signup/__tests__/EditSignupPage.test.tsx
src/domain/signup/modals/sendMessageModal/__tests__/SendMessageModal.test.tsx
src/domain/signupGroup/__tests__/EditSignupGroupPage.test.tsx
src/domain/signups/__tests__/SignupsPage.test.tsx
src/domain/signups/signupActionsDropdown/__tests__/SignupActionsDropdown.test.tsx
yarn.lock

Bump @ckeditor/ckeditor5-build-classic to 43.1.1. This fixes two vulnerabilities:
- https://github.com/City-of-Helsinki/linkedcomponents-ui/security/dependabot/149
- https://github.com/City-of-Helsinki/linkedcomponents-ui/security/dependabot/151
**[LINK-2191](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2191):**
[LINK-2191]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

deps: bump @ckeditor/ckeditor5-build-classic to 43.1.1 LINK-2191

---

src/domain/auth/constants.ts
src/domain/event/eventForm/EventForm.tsx

- Use login provider session polling default setting (60s) instead of 10s.
- Don't validate event form on change, this makes filling the form heavy
**[LINK-2179](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2179):**
[LINK-2179]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: loginProvider use sessionPoller default settings LINK-2179

---

vite.config.ts

Setting ROLLUP_INLINE_DYNAMIC_IMPORTS=true will essentially create a single js and css file.
The reason for introducing this is that platta has implemented DDoS protection that gets easily upset because normal rollup build produces quite many js and css assets. This becomes very problematic with playwright tests that make a lot of repeated requests.
refs: LINK-2229
Co-PR: https://dev.azure.com/City-of-Helsinki/linkedevents/_git/linkedevents-pipelines/pullrequest/10597

fix: add support for inlining via ROLLUP_INLINE_DYNAMIC_IMPORTS

---

src/domain/attendanceList/attendeeList/AttendeeList.tsx

refs: LINK-2220
co-pr: https://github.com/City-of-Helsinki/linkedregistrations-ui/pull/207

fix: sort attendees by id (from oldest to newest) instead of name

---

Dockerfile

ubi8/nginx-120 has been deprecated long time ago. ubi9/nginx-120 is actively maintained.
refs: LINK-2221

fix: use ubi9/nginx-120

---

src/constants.ts
src/domain/app/footer/Footer.tsx
src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap
src/domain/app/hooks/useCookieConsentSettings.ts
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/app/layout/pageWrapper/PageWrapper.tsx
src/domain/app/routes/localeRoutes/LocaleRoutes.tsx

- New cookie banner is missing functionality to enable/disable Matomo tracking.
- Add cookies page that has been previously missing
**[LINK-1759](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1759):**
[LINK-1759]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cookies fixes LINK-1759

---

src/domain/event/eventForm/EventForm.tsx
src/domain/event/formSections/priceSection/PriceSection.tsx
src/domain/event/formSections/priceSection/__tests__/PriceSection.test.tsx

**[LINK-2257](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2257):**
Admin user sees this:
Non admin sees this:
[LINK-2257]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: only admin can see add registration checkbox LINK-2257

---

src/domain/event/utils.ts

Initial edu keywords should be an empty array if not defined. Currently this breaks saving copied event.
**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX):**

fix: initial edu keywords empty array Ref: LINK-2388

---

src/domain/event/utils.ts

External user should be able to create events with offers, but then offer price groups should not be included. Filtering out the base price groups if price or vat percentage values don't exist.
**[LINK-2403](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2403):**
[LINK-2403]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: price group logic for external events Ref: LINK-2403

---

src/domain/event/validation.ts
src/utils/validationUtils.ts

Continuation of https://github.com/City-of-Helsinki/linkedcomponents-ui/pull/513.
Fixing the validation rules so that we check that event re is planned and the vat percentage value exists.
**[LINK-2403](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2403):**
[LINK-2403]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: price group validation only when vat exists Ref: LINK-2403
