src/assets/styles/breakpoints.scss
src/assets/theme/theme.ts
src/common/components/button/Button.tsx
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/app/layout/Container.tsx
src/domain/app/layout/PageLayout.tsx
src/domain/app/layout/container.module.scss
src/domain/app/layout/pageLayout.module.scss
src/domain/app/theme/Theme.tsx
src/domain/event/CreateEventPage.tsx
src/domain/event/__tests__/CreateEventPage.test.tsx
src/domain/event/eventNavigation/EventNavigation.tsx
src/domain/event/eventNavigation/__tests__/EventNavigation.test.tsx
src/domain/event/eventNavigation/eventNavigation.module.scss

Component to navigate between event form pages
**[LINK-71](https://helsinkisolutionoffice.atlassian.net/browse/LINK-71)**

LINK-71 | Event page navigation

---

src/domain/app/i18n/constants.ts
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/EditEventPage.tsx
src/domain/event/formSections/additionalInfoSection/AdditionalInfoSection.tsx
src/domain/event/formSections/classificationSection/ClassificationSection.tsx
src/domain/event/formSections/classificationSection/__tests__/ClassificationSection.test.tsx
src/domain/event/formSections/descriptionSection/DescriptionSection.tsx
src/domain/event/formSections/imageSection/ImageSection.tsx
src/domain/event/formSections/responsibilitiesSection/ResponsibilitiesSection.tsx
src/domain/event/formSections/timeSection/EventTime.tsx
src/domain/event/formSections/timeSection/EventTimes.tsx
src/domain/event/formSections/timeSection/TimeSection.tsx
src/domain/event/formSections/timeSection/__tests__/EventTime.test.tsx
src/domain/event/formSections/timeSection/__tests__/TimeSection.test.tsx
src/domain/event/formSections/timeSection/recurringEventsForm/RecurringEventsForm.tsx
src/domain/event/formSections/typeSection/TypeSection.tsx
src/domain/event/utils.ts

Update event form instruction texts
[LINK-334](https://helsinkisolutionoffice.atlassian.net/browse/LINK-334)

LINK-334 | Updating event form instruction text

---

package.json
src/common/components/imageUploader/ImageUploader.tsx
src/common/components/imageUploader/__tests__/ImageUploader.test.tsx
src/constants.ts
yarn.lock

Compress images (max size 2 MB) before uploading them to LE
[LINK-343](https://helsinkisolutionoffice.atlassian.net/browse/LINK-343)
Can be tested at http://localhost:3000/fi/events/create by adding a large image ( size > 2 MB) to an event

LINK-343 | Compress images before uploading them to LE

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/CreateEventPage.tsx
src/domain/event/EditEventPage.tsx
src/domain/event/authRequiredNotification/AuthRequiredNotification.tsx
src/domain/event/authRequiredNotification/__tests__/AuthRequiredNotification.test.tsx
src/domain/event/authRequiredNotification/authRequiredNotification.module.scss
src/domain/event/eventPage.module.scss

Show notification in create/edit event page if
- user is not logged in
- user doesn't have permissions to any organisations
[LINK-531](https://helsinkisolutionoffice.atlassian.net/browse/LINK-531)

LINK-531 | Not logged in notification

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/app/layout/TitleRow.tsx
src/domain/app/layout/titleRow.module.scss
src/domain/enrolment/CreateEnrolmentPage.tsx
src/domain/enrolment/EditEnrolmentPage.tsx
src/domain/enrolment/enrolmentPage.module.scss
src/domain/enrolments/EnrolmentsPage.tsx
src/domain/enrolments/enrolmentsPage.module.scss
src/domain/event/CreateEventPage.tsx
src/domain/event/EditEventPage.tsx
src/domain/event/eventPage.module.scss
src/domain/events/EventsPage.tsx
src/domain/events/events.module.scss
src/domain/registration/CreateRegistrationPage.tsx
src/domain/registration/EditRegistrationPage.tsx
src/domain/registration/registrationPage.module.scss
src/domain/registrations/RegistrationsPage.tsx
src/domain/registrations/registrations.module.scss

Add breadcrumbs to pages where it's missing
[LINK-846](https://helsinkisolutionoffice.atlassian.net/browse/LINK-846)

LINK-846 | Add breadcrumbs to pages where it's missing

---

package.json
src/common/components/imageUploader/ImageUploader.tsx
src/common/components/imageUploader/__tests__/ImageUploader.test.tsx
src/common/components/imageUploader/contants.ts
src/common/components/imageUploader/imageCropper/ImageCropper.tsx
src/common/components/imageUploader/imageDropzone/ImageDropzone.tsx
src/common/components/imageUploader/imageDropzone/imageDropzone.module.scss
src/common/components/imageUploader/imageUploader.module.scss
src/common/components/imageUploader/utils.ts
src/constants.ts
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/formSections/imageSection/ImageSection.tsx
src/domain/event/formSections/imageSection/__tests__/ImageSection.test.tsx
src/domain/image/__mocks__/createImagePage.ts
src/domain/image/__tests__/CreateImagePage.test.tsx
src/domain/image/addImageForm/AddImageForm.tsx
src/domain/image/addImageForm/__tests__/AddImageForm.test.tsx
src/domain/image/constants.tsx
src/domain/image/imageForm/ImageForm.tsx
src/domain/image/modals/addImageModal/AddImageModal.tsx
src/domain/image/types.ts
src/domain/image/validation.ts
src/domain/organizationClass/organizationClassName/OrganizationClassName.tsx
yarn.lock

Support image cropping before uploading an image to the server
[LINK-346](https://helsinkisolutionoffice.atlassian.net/browse/LINK-346)

LINK-346 | Image cropping

---

src/common/components/comboboxLoadingSpinner/ComboboxLoadingSpinner.tsx
src/common/components/comboboxLoadingSpinner/comboboxLoadingSpinner.module.scss
src/common/components/eventSelector/.eventSelector.module.scss
src/common/components/eventSelector/EventSelector.tsx
src/common/components/keywordSelector/KeywordSelector.tsx
src/common/components/placeSelector/PlaceSelector.tsx
src/common/components/singleKeywordSelector/SingleKeywordSelector.tsx
src/constants.ts
src/domain/eventSearch/searchPanel/placeSelector/PlaceSelector.tsx
src/utils/testUtils.tsx

Add debounce to selectors which are getting data from API
Show loading spinner when loading data
[LINK-906](https://helsinkisolutionoffice.atlassian.net/browse/LINK-906)

LINK-906 | Debounce for dropdown selectors

---

src/domain/event/__mocks__/createEventPage.ts
src/domain/event/__tests__/utils.test.ts
src/domain/event/__tests__/validation.test.ts
src/domain/event/constants.tsx
src/domain/event/formSections/priceSection/PriceSection.tsx
src/domain/event/formSections/priceSection/__tests__/PriceSection.test.tsx
src/domain/event/formSections/priceSection/freeEventFields/FreeEventFields.tsx
src/domain/event/formSections/priceSection/offers/Offers.tsx
src/domain/event/formSections/priceSection/offers/offer/Offer.tsx
src/domain/event/formSections/priceSection/priceNotification/PriceNotification.tsx
src/domain/event/hooks/__tests__/useUpdateRecurringEventIfNeeded.test.tsx
src/domain/event/utils.ts
src/domain/event/validation.ts

Show info url fields also to free events
[LINK-918](https://helsinkisolutionoffice.atlassian.net/browse/LINK-918)

LINK-918 | Show info url fields also to free events

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/formSections/descriptionSection/DescriptionSection.tsx
src/domain/event/formSections/placeSection/PlaceSection.tsx

Improve event description and location instruction texts
[LINK-972](https://helsinkisolutionoffice.atlassian.net/browse/LINK-972)

LINK-972 | Improve instruction texts

---

.vscode/settings.json
src/domain/app/App.tsx
src/domain/app/__tests__/App.test.tsx
src/domain/app/cookieConsent/CookieConsent.tsx
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/hooks/useSelectLanguage.ts

Move cookie consent modal translations to the localisation files
[LINK-1050](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1050)

LINK-1050 | Move cookie consent modal translations to the localisation files

---

src/common/components/fieldset/Fieldset.tsx
src/common/components/fieldset/fieldset.module.scss
src/common/components/formFields/checkboxGroupField/checkboxGroupField.module.scss
src/common/components/formFields/radioButtonGroupField/radioButtonGroupField.module.scss
src/domain/enrolment/enrolmentFormFields/EnrolmentFormFields.tsx
src/domain/event/formSections/additionalInfoSection/AdditionalInfoSection.tsx
src/domain/event/formSections/audienceSection/AudienceSection.tsx
src/domain/event/formSections/channelsSection/ChannelsSection.tsx
src/domain/event/formSections/classificationSection/ClassificationSection.tsx
src/domain/event/formSections/descriptionSection/DescriptionSection.tsx
src/domain/event/formSections/imageSection/ImageSection.tsx
src/domain/event/formSections/languagesSection/LanguagesSection.tsx
src/domain/event/formSections/placeSection/PlaceSection.tsx
src/domain/event/formSections/priceSection/PriceSection.tsx
src/domain/event/formSections/responsibilitiesSection/ResponsibilitiesSection.tsx
src/domain/event/formSections/timeSection/eventTimeTab/EventTimeTab.tsx
src/domain/event/formSections/timeSection/recurringEventTab/RecurringEventTab.tsx
src/domain/event/formSections/typeSection/TypeSection.tsx
src/domain/event/formSections/videoSection/VideoSection.tsx
src/domain/registration/formSections/attendeeCapacitySection/AttendeeCapacitySection.tsx
src/domain/registration/formSections/audienceAgeSection/AudienceAgeSection.tsx
src/domain/registration/formSections/confirmationMessageSection/ConfirmationMessageSection.tsx
src/domain/registration/formSections/enrolmentTimeSection/EnrolmentTimeSection.tsx
src/domain/registration/formSections/eventSection/EventSection.tsx
src/domain/registration/formSections/instructionsSection/InstructionsSection.tsx
src/domain/registration/formSections/requiredFieldsSection/RequiredFieldsSection.tsx
src/domain/registration/formSections/waitingListSection/WaitingListSection.tsx

Group fields in registration form using HDS Fieldset component
Group fields in event form using HDS Fieldset component
[LINK-1098](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1098)
[LINK-1098]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LINK-1098]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1098 | Group fields using HDS Fieldset component

---

src/common/components/comboboxLoadingSpinner/ComboboxLoadingSpinner.tsx
src/common/components/comboboxLoadingSpinner/comboboxLoadingSpinner.module.scss
src/common/components/singleOrganizationSelector/SingleOrganizationSelector.tsx
src/constants.ts
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/app/routes/helpPageRoutes/HelpPageRoutes.tsx
src/domain/help/constants.ts
src/domain/help/hooks/useFeedbackActions.ts
src/domain/help/layout/HelpPageLayout.tsx
src/domain/help/pages/askPermissionPage/AskPermissionPage.tsx
src/domain/help/pages/askPermissionPage/__tests__/AskPermissionPage.test.tsx
src/domain/help/pages/contactPage.module.scss
src/domain/help/pages/contactPage/ContactPage.tsx
src/domain/help/pages/contactPage/__tests__/ContactPage.test.tsx
src/domain/help/types.ts
src/domain/help/utils.ts
src/domain/help/validation.ts
src/domain/organization/organizationForm/OrganizationForm.tsx

Page to ask permissions to a selected organization
[LINK-1104](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1104)
[LINK-1104]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1104 | Page to ask permissions to a selected organization

---

src/domain/image/__tests__/utils.test.ts
src/domain/image/utils.ts
src/domain/organization/utils.ts

Allow all image publisher admin users to delete the image
NOTE! There is an open PR to implement same changes to backend at https://github.com/City-of-Helsinki/linkedevents/pull/564 
[LINK-1057](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1057)
[LINK-1057]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1057 | Allow all image publisher admin users to delete the image

---

src/assets/theme/theme.ts
src/common/components/buttonPanel/buttonPanel.module.scss
src/common/components/combobox/Combobox.tsx
src/common/components/comboboxLoadingSpinner/ComboboxLoadingSpinner.tsx
src/common/components/dropdown/dropdown.module.scss
src/common/components/eventSelector/EventSelector.tsx
src/common/components/keywordSelector/KeywordSelector.tsx
src/common/components/map/map.module.scss
src/common/components/menuDropdown/menu/menu.module.scss
src/common/components/modal/modal.module.scss
src/common/components/notification/Notification.tsx
src/common/components/notification/notification.module.scss
src/common/components/placeSelector/PlaceSelector.tsx
src/common/components/publisherSelector/PublisherSelector.tsx
src/common/components/singleKeywordSelector/SingleKeywordSelector.tsx
src/common/components/singleOrganizationClassSelector/SingleOrganizationClassSelector.tsx
src/common/components/singleOrganizationSelector/SingleOrganizationSelector.tsx
src/domain/app/header/header.module.scss
src/domain/app/theme/Theme.tsx
src/domain/image/imageForm/ImageForm.tsx
src/domain/keyword/keywordForm/KeywordForm.tsx
src/domain/keywordSet/keywordSetForm/KeywordSetForm.tsx
src/domain/organization/organizationForm/OrganizationForm.tsx
src/domain/place/placeForm/PlaceForm.tsx

Fix z-indexes
Fix loading spinner position in comboboxes of admin forms
[LINK-1244](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1244)
[LINK-1244]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1244 | Minor style fixes

---

src/domain/auth/__tests__/utils.test.ts
src/domain/registration/editButtonPanel/__tests__/EditButtonPanel.test.tsx
src/domain/registrations/registrationActionsDropdown/__tests__/RegistrationActionsDropdown.test.tsx

Remove environment variable dependent check from unit tests
[LINK-1331](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1331)
[LINK-1331]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1331 | Fix unit tests

---

schema.js
src/domain/app/routes/localeRoutes/__tests__/LocaleRoutes.test.tsx
src/domain/enrolment/__tests__/CreateEnrolmentPage.test.tsx
src/domain/enrolment/__tests__/EditEnrolmentPage.test.tsx
src/domain/enrolment/enrolmentFormFields/EnrolmentFormFields.tsx
src/domain/enrolment/hooks/useLanguageOptions.ts
src/domain/event/__tests__/CreateEventPage.test.tsx
src/domain/event/__tests__/EditEventPage.test.tsx
src/domain/event/formSections/languagesSection/LanguagesSection.tsx
src/domain/event/hooks/useEventFieldOptionsData.ts
src/domain/language/__mocks__/language.ts
src/domain/language/__tests__/utils.test.ts
src/domain/language/query.ts
src/domain/language/utils.ts
src/generated/graphql.tsx
src/utils/mockDataUtils.ts

Allow to select only languages where service_language is true as enrolment service language
Fix failing unit test in create event page
PR for API: https://github.com/City-of-Helsinki/linkedevents/pull/619
[LINK-1368](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1368)
[LINK-1368]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1368 | Enrolment form service language

---

src/domain/events/eventsTable/eventsTable.module.scss
src/domain/events/eventsTable/eventsTableRow/EventsTableRow.tsx
src/domain/events/eventsTable/eventsTableRow/__tests__/EventsTableRow.test.tsx
src/domain/organization/__mocks__/organization.ts
src/domain/organization/__mocks__/organizationAncestors.ts
src/domain/organization/constants.tsx

Amazing blob to highlight if event is from external publisher.
Translations for external required?
**[LINK-1036](LINK-1036):**
[LINK-1036]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature: Highlighting publisher if event was created by external user.

---

src/domain/event/constants.tsx
src/domain/event/formSections/audienceSection/__tests__/AudienceSection.test.tsx
src/domain/event/hooks/__tests__/utils.test.ts
src/domain/event/hooks/useAudienceOptions.ts
src/domain/event/hooks/utils.ts

Sort order for audiences was previously hardcoded. This commit changes it to locale based alphabetical sorting.
Ref LINK-1461

Sort audiences alphabetically

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/app/routes/helpPageRoutes/__tests__/HelpPageRoutes.test.tsx
src/domain/app/routes/localeRoutes/__tests__/LocaleRoutes.test.tsx
src/domain/help/pages/termsOfUsePage/TermsOfUsePage.tsx
src/domain/help/pages/termsOfUsePage/termsOfUsePage.module.scss

This PR updates Term Of Use -page texts
**[LINK-1388](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1388):**
Tested locally
[LINK-1388]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1388 | Updated Terms of Use -page information

---

browser-tests/help/help.components.ts

Fix e2e terms of use title selector
**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX):**

LINK-1388 e2e fix terms of use title selector

---

src/domain/app/i18n/en.json

Minor translation fixes
**[LINK-1342](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1342):**
[LINK-1342]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1342 Minor translation fixes

---

src/utils/__tests__/validationUtils.test.ts
src/utils/validationUtils.ts

Improve phone number validation to allow e.g. +358 44 1234 567 which is used as placeholder text
[LINK-1530](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1530)
[LINK-1530]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1530 | Improve phone number validation

---

src/domain/registration/__tests__/utils.test.ts
src/domain/registration/utils.ts

Include confirmation message and instructions in all the selected info languages to registration payload
[LINK-1481](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1481)
[LINK-1481]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1481 |. Registration confirmation message and instructions

---

schema.js
src/domain/signup/__mocks__/editSignupPage.ts
src/domain/signup/hooks/useSignupActions.ts
src/domain/signup/modals/sendMessageModal/SendMessageModal.tsx
src/domain/signup/modals/sendMessageModal/__tests__/SendMessageModal.test.tsx
src/domain/signupGroup/__mocks__/editSignupGroupPage.ts
src/domain/signupGroup/__tests__/EditSignupGroupPage.test.tsx
src/domain/signupGroup/signupGroupForm/SignupGroupForm.tsx
src/generated/graphql.tsx

Use signup_groups attribute when sending message to a signup group
[LINK-1609](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1609)
[LINK-1609]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1609 | Use signup_groups attribute when sending message to a signup group

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/registration/hooks/__tests__/useRegistrationServerErrors.test.tsx
src/domain/signupGroup/participantAmountSelector/__tests__/ParticipantAmountSelector.test.tsx
src/domain/signupGroup/reservationTimer/__tests__/ReservationTimer.test.tsx
src/domain/signupGroup/signupGroupFormFields/signups/signup/signupAccordion/__tests__/SignupAccordion.test.tsx

Replace term "varasija" with "jono"
[LINK-1636](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1636)
[LINK-1636]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1636 | Replace term "varasija" with "jono"

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/registration/__tests__/utils.test.ts
src/domain/registration/types.ts
src/domain/registration/utils.ts
src/domain/registrations/registrationList/registrationList.module.scss
src/domain/registrations/registrationsTable/RegistrationsTable.tsx
src/domain/registrations/registrationsTable/__tests__/RegistrationsTable.test.tsx
src/domain/registrations/registrationsTable/registrationsTable.module.scss
src/domain/registrations/registrationsTable/timeText/TimeText.tsx
src/domain/registrations/registrationsTable/timeText/__tests__/TimeText.test.tsx
src/domain/registrations/registrationsTable/timeText/__tests__/__snapshots__/TimeText.test.tsx.snap
src/domain/registrations/registrationsTable/timeText/timeText.module.scss
src/utils/getNumberFieldValue.ts

- Show maximum attendee count and waiting list capacity only if defined
- Add event time to registrations table
- Display enrolment start and end time in same column
[LINK-1582](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1582)
[LINK-1582]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1582 | Registration table improvements

---

src/domain/app/header/Header.tsx
src/domain/app/layout/pageLayout/PageLayout.tsx
src/domain/attendanceList/AttendanceListPage.tsx
src/domain/attendanceList/attendanceListPage.module.scss
src/domain/signups/SignupsPage.tsx
src/domain/signups/signupsPage.module.scss

Back button to attendance list page
[LINK-1616](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1616)
[LINK-1616]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1616 | Back button to attendance list page

---

src/assets/theme/theme.ts
src/common/components/errorPage/ErrorPage.tsx
src/common/components/errorPage/__tests__/__snapshots__/ErrorPage.test.tsx.snap
src/common/components/errorPage/errorPage.module.scss
src/common/components/errorTemplate/ErrorTemplate.tsx
src/common/components/errorTemplate/errorTemplate.module.scss
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/app/theme/Theme.tsx
src/domain/registration/__mocks__/registration.ts
src/domain/registration/__tests__/utils.test.ts
src/domain/registration/utils.ts
src/domain/registrations/registrationsTable/timeText/__tests__/TimeText.test.tsx
src/domain/signupGroup/CreateSignupGroupPage.tsx
src/domain/signupGroup/__tests__/CreateSignupGroupPage.test.tsx
src/domain/signupGroup/signupIsEnded/SignupIsEnded.tsx
src/domain/signupGroup/signupIsEnded/__tests__/SignupIsEnded.test.tsx

Show "Ilmoittautuminen tapahtumaan on päättynyt" text instead of signup form is enrolment is already closed
[LINK-1607](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1607)
[LINK-1607]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1607 | Don't show signup form if signup is already closed

---

browser-tests/footer/footer.components.ts
browser-tests/header/header.components.ts
browser-tests/header/header.testcafe.ts

Fixing header and footer E2E tests
**[LINK-1635](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1635):**
[LINK-1635]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LINK-1635] fix: fixing header and footer e2e tests

---

azure-pipelines-build-prod.yml
azure-pipelines-build-staging.yml

Stage and prod pipelines are triggered from tag named 'release-*'
**[LINK-1711](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1711):**
[LINK-1711]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build: prod and stage pipelines are triggered from tag LINK-1711

---

browser-tests/footer/footer.components.ts
browser-tests/header/header.components.ts
browser-tests/header/header.testcafe.ts
src/domain/app/footer/Footer.tsx
src/domain/app/footer/__tests__/Footer.test.tsx
src/domain/app/footer/footer.module.scss
src/domain/app/header/Header.tsx
src/domain/app/header/__tests__/Header.test.tsx
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json

Fixes to previously implemented hds-react V3 components:
- Header: move Search events link to navigation, since scaling action bar items does work very well at the moment. Also use the same translation for both Header and Footer
- Support page: fix Footer koros (wave), use white Helsinki logo
**[LINK-1635](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1635):**
[LINK-1635]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1635 HDS component fixes

---

.env.local.example
README.md

This PR fixes the documented configuration for the backend.

Improve instructions for local tunnistamo setup

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/signupGroup/__tests__/CreateSignupGroupPage.test.tsx
src/domain/signupGroup/createButtonPanel/__tests__/CreateSignupGroupButtonPanel.test.tsx
src/domain/signupGroup/signupGroupForm/SignupGroupForm.tsx

Linked Registration UI uses "Lähetä ilmoittautuminen" as create signup button label. Use it LE UI as well.

fix: Unify create signup button label

---

src/common/components/buttonPanel/buttonPanel.module.scss
src/common/components/table/table.module.scss
src/common/components/table/tableWrapper/TableWrapper.tsx
src/domain/events/eventCard/eventCard.module.scss
src/domain/events/eventList/EventList.tsx
src/domain/events/eventList/eventList.module.scss
src/domain/registrations/registrationList/RegistrationList.tsx
src/domain/registrations/registrationList/registrationList.module.scss

- Support background inlining in TableWrapper component and use display grid to avoid screen overflow
- Have button panel submit buttons in separate rows to avoid screen overflow
- Fix event card overflow issues
[LINK-1753](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1753)
[LINK-1753]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1753 | Fix screen overflow issues for small screen

---

src/common/components/combobox/Combobox.tsx
src/common/components/eventSelector/EventSelector.tsx
src/common/components/imageSelector/ImageSelector.tsx
src/common/components/keywordSelector/KeywordSelector.tsx
src/common/components/loadingSpinner/LoadingSpinner.tsx
src/common/components/multiSelectDropdown/MultiSelectDropdown.tsx
src/common/components/numberInput/NumberInput.tsx
src/common/components/placeSelector/PlaceSelector.tsx
src/common/components/publisherSelector/PublisherSelector.tsx
src/common/components/searchInput/SearchInput.tsx
src/common/components/singleKeywordSelector/SingleKeywordSelector.tsx
src/common/components/singleOrganizationClassSelector/SingleOrganizationClassSelector.tsx
src/common/components/singleOrganizationSelector/SingleOrganizationSelector.tsx
src/common/components/userSelector/UserSelector.tsx
src/domain/app/authenticationNotification/AuthenticationNotification.tsx
src/domain/app/cookieConsent/CookieConsent.tsx
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/auth/logoutPage/LogoutPage.tsx
src/domain/event/eventForm/EventForm.tsx
src/domain/eventSaved/EventSavedPage.tsx
src/domain/help/pages/platformPage/PlatformPage.tsx
src/domain/landingPage/LandingPage.tsx
src/domain/landingPage/serviceCard/ServiceCard.tsx
src/domain/notFound/NotFound.tsx
src/domain/registrationSaved/RegistrationSavedPage.tsx

Give aria-label for combobox clear button to improve accessibility
[LINK-1764](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1764)
[LINK-1764]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1764 | Add aria-label for combobox clear button

---

schema.js
src/domain/event/hooks/__tests__/useUpdateRecurringEventIfNeeded.test.tsx
src/domain/organization/__mocks__/organizationAncestors.ts
src/domain/organization/hooks/__tests__/useAllOrganizations.test.tsx
src/domain/organization/hooks/useAllOrganizations.ts
src/domain/organization/hooks/useOrganizationAncestors.ts
src/domain/organization/query.ts
src/domain/organization/utils.ts
src/domain/organizations/__mocks__/organizationsPage.ts
src/generated/graphql.tsx

Don't show dissolved organizations
**[LINK-1716](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1716):**
Tested on local machine, unit testing
[LINK-1716]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: don't show dissolved organizations LINK-1716

---

schema.js
src/common/components/publisherSelector/PublisherSelector.tsx
src/common/components/publisherSelector/__tests__/PublisherSelector.test.tsx
src/domain/organization/EditOrganizationPage.tsx
src/domain/organization/__mocks__/organization.ts
src/domain/organization/organizationName/OrganizationName.tsx
src/domain/organization/query.ts
src/domain/organization/utils.ts
src/generated/graphql.tsx

Same change as in https://github.com/City-of-Helsinki/linkedcomponents-ui/pull/291 but for single organization paths.
**[LINK-1716](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1716):**
Tested on local machine, unit testing
[LINK-1716]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: don't show single dissolved organizations LINK-1716

---

src/domain/registration/constants.ts
src/domain/registration/formSections/mandatoryFieldsSection/MandatoryFieldsSection.tsx

Remove phone_number from mandatory fields

fix: Remove phone_number from mandatory fields

---

src/domain/app/i18n/en.json
src/domain/app/i18n/sv.json
src/domain/app/routes/helpPageRoutes/__tests__/HelpPageRoutes.test.tsx
src/domain/help/pages/termsOfUsePage/TermsOfUsePage.tsx
src/domain/help/pages/termsOfUsePage/termsOfUsePage.module.scss

Update terms of use page content
[LINK-1778](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1778)
[LINK-1778]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1778 | Update terms of use page content

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json

Changed maintenance notification texts in three languages as requested in [JIRA LINK-1828](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1828)

LINK-1828 Add new maintenance notification texts

---

src/domain/signupGroup/__tests__/validation.test.ts
src/domain/signupGroup/validation.ts

- Allow user to signup if user is old enough in the event start time
- Prevent user to signup if user is too old in the event start time
[LINK-1847](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1847)
[LINK-1847]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1847 | Use event start time for signup birth of date validation

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json

Just change p -tags to br -tags [Jira LINK-1828](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1828)

LINK-1828 modify maintenance notification texts

---

src/constants.ts
src/domain/app/layout/splittedRow/SplittedRow.tsx
src/domain/app/layout/splittedRow/splittedRow.module.scss
src/domain/registration/__mocks__/registration.ts
src/domain/signupGroup/__tests__/CreateSignupGroupPage.test.tsx
src/domain/signupGroup/__tests__/testUtils.ts
src/domain/signupGroup/__tests__/validation.test.ts
src/domain/signupGroup/signupGroupFormFields/signups/signup/Signup.tsx
src/domain/signupGroup/signupGroupFormFields/signups/signup/__test__/Signup.test.tsx
src/domain/signupGroup/signupGroupFormFields/signups/signup/signup.module.scss
src/domain/signupGroup/validation.ts

We want to collect data only for the mandatory fields so hide all the signup fields which are not set to be mandatory
[LINK-1805](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1805)
[LINK-1805]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1805 | Display only mandatory signup fields

---

azure-pipelines-acceptance-tests.yml
azure-pipelines-build-devtest.yml
azure-pipelines-build-prod.yml
azure-pipelines-build-staging.yml
azure-pipelines-e2e-dev.yml
azure-pipelines-e2e-prod.yml
pipelines/linkedcomponents-ui-dev.yml
pipelines/linkedcomponents-ui-release.yml
pipelines/linkedcomponents-ui-review.yml

[OH-35](https://helsinkisolutionoffice.atlassian.net/browse/OH-35)
**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX):**
[OH-35]: https://helsinkisolutionoffice.atlassian.net/browse/OH-35?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build: pipeline upgrade

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/auth/oidcCallback/OidcCallback.tsx

Display notification in case of access denied error
[LINK-1867](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1867)
[LINK-1867]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1867 | Display notification in case of access denied error

---

src/domain/app/apollo/utils.ts
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/modals/confirmCancelEventModal/ConfirmCancelEventModal.tsx
src/domain/event/modals/confirmCancelEventModal/__tests__/ConfirmCancelEventModal.test.tsx
src/domain/event/modals/confirmDeleteEventModal/ConfirmDeleteEventModal.tsx
src/domain/event/modals/confirmDeleteEventModal/__tests__/ConfirmDeleteEventModal.test.tsx

Improve texts in cancel/delete event modals
[LINK-1819](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1819)
[LINK-1819]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1819 | Improve texts in cancel/delete event modals

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/formSections/descriptionSection/DescriptionSection.tsx

Add notification for environment certificate fields
[LINK-1901](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1901)
[LINK-1901]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1901 | Add notification for environment certificate fields

---

src/common/components/formFields/registrationEventSelectorField/RegistrationEventSelectorField.tsx
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/formSections/registrationSection/RegistrationSection.tsx
src/domain/events/utils.ts
src/domain/registration/formSections/eventSection/EventSection.tsx
src/domain/registration/formSections/eventSection/__mocks__/eventSection.ts
src/domain/registration/formSections/eventSection/__tests__/EventSection.test.tsx

Add checkbox to show recurring events in the registration form
Allow to select recurring event in registration form and create a registration for it
[LINK-1883](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1883)
[LINK-1883]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1883 | allow to create registration for a recurring event

---

src/common/components/accordion/Accordion.tsx
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/constants.tsx
src/domain/events/__tests__/utils.test.ts
src/domain/events/utils.ts
src/domain/signupGroup/eventInfo/EventInfo.tsx
src/domain/signupGroup/eventInfo/EventTimes.tsx
src/domain/signupGroup/eventInfo/__tests__/EventTimes.test.tsx
src/domain/signupGroup/eventInfo/eventInfo.module.scss
src/domain/signupGroup/hooks/useEventWithSubEventsData.ts

Display event times for recurring event in a signup form
[LINK-1884](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1884)
[LINK-1884]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1884 | Add event times to signup form

---

src/common/components/table/table.module.scss
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/__tests__/EditEventPage.test.tsx
src/domain/event/formSections/timeSection/__tests__/TimeSection.test.tsx
src/domain/event/formSections/timeSection/eventTimeTab/__tests__/EventTimeTab.test.tsx
src/domain/event/formSections/timeSection/eventTimesSummary/EventTimesSummary.tsx
src/domain/event/formSections/timeSection/eventTimesSummary/__tests__/EventTimesSummary.test.tsx
src/domain/event/formSections/timeSection/eventTimesTable/EventTimesTable.tsx
src/domain/event/formSections/timeSection/eventTimesTable/__tests__/EventTimesTable.test.tsx
src/domain/event/formSections/timeSection/recurringEvents/RecurringEvents.tsx
src/domain/event/formSections/timeSection/recurringEvents/__tests__/RecurringEvents.test.tsx
src/domain/event/formSections/timeSection/recurringEvents/recurringEvent/RecurringEvent.tsx
src/domain/event/formSections/timeSection/timeSection.module.scss

- Remove index column
- Update heading of actions column
- Change font size to 0 in actions column.
[LINK-1762](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1762)
[LINK-1762]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1762 | improve event times table accessibility

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/formSections/priceSection/__tests__/PriceSection.test.tsx
src/domain/event/formSections/videoSection/__tests__/VideoSection.test.tsx
src/domain/registration/formSections/priceGroups/__tests__/PriceGroupSection.test.tsx
src/domain/registration/formSections/registrationUserAccessesSection/__tests__/RegistrationUserAccessesSection.test.tsx

- Replace "Lisää hintatieto" with "Lisää muita hintatietoja"
- Replace "Lisää video" with "Lisää muita videoita"
- Replace "Lisää uusi asiakasryhmä" with "Lisää muita asiakasryhmiä"
- Replace "Lisää uusi käyttäjä" with "Lisää muita käyttäjiä"
[LINK-1763](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1763)
[LINK-1763]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1763 | Improve add button texts

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/signup/constants.tsx
src/domain/signupGroup/modals/reservationTimeExpiringModal/ReservationTimeExpiringModal.tsx
src/domain/signupGroup/reservationTimer/ReservationTimer.tsx
src/domain/signupGroup/reservationTimer/__tests__/ReservationTimer.test.tsx

- Display accessibility notification after loading reservation timer. Text tells to user how much time there is to register.
- Display modal if registration time is expiring soon
[LINK-1754](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1754)
[LINK-1754]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1754 | Modal before reservation time is expiring

---

src/domain/signupGroup/__tests__/CreateSignupGroupPage.test.tsx
src/domain/signupGroup/__tests__/validation.test.ts
src/domain/signupGroup/signupGroupFormFields/SignupGroupFormFields.tsx
src/domain/signupGroup/validation.ts

Change the native language field to optional
[LINK-1978](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1978)
[LINK-1978]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1978 | Change the native language field to optional

---

.commitlintrc.json
.github/workflows/ci.yml
.husky/commit-msg
README.md
package.json
yarn.lock

Add commit lint to the project
[LINK-1961](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1961)
[LINK-1961]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1961 | add commit lint to the project

---

src/domain/registration/__tests__/utils.test.ts
src/domain/registration/utils.ts
src/domain/signupGroup/CreateSignupGroupPage.tsx
src/domain/signupGroup/__tests__/CreateSignupGroupPage.test.tsx
src/domain/signupGroup/__tests__/permissions.test.ts
src/domain/signupGroup/permissions.ts
src/domain/signupGroup/registrationWarning/RegistrationWarning.tsx
src/domain/signupGroup/registrationWarning/__tests__/RegistrationWarning.test.tsx
src/domain/signupGroup/signupGroupForm/SignupGroupForm.tsx

Allow registration admin to signup to a closed registration in the case that there still are available seats
[LINK-1948](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1948)
[LINK-1948]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1948 | allow registration admin to signup to a closed registration

---

schema.js
src/domain/signup/__tests__/utils.test.ts
src/domain/signup/utils.ts
src/domain/signupGroup/__tests__/utils.test.ts
src/domain/signupGroup/__tests__/validation.test.ts
src/domain/signupGroup/signupGroupForm/SignupGroupForm.tsx
src/domain/signupGroup/signupGroupFormFields/SignupGroupFormFields.tsx
src/domain/signupGroup/utils.ts
src/domain/signupGroup/validation.ts
src/generated/graphql.tsx

Validate that contact person first name and last name are filled if the payment is needed for the signup.
Create payment if the signup group or signup group price is higher that 0
[LINK-2082](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2082)
[LINK-2082]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2082 | Validate contact person name fields

---

src/domain/accessibilityStatement/AccessibilityStatement.tsx

Update accessibility statement page content to match current situation.
[LINK-1990](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1990)
[LINK-1990]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1990 | update accessibility statement

---

src/domain/admin/layout/hooks/useAdminFormStyles.ts
src/domain/place/placeForm/PlaceForm.tsx
src/domain/priceGroup/priceGroupForm/PriceGroupForm.tsx

Use useAdminFormStyles hook to remove duplicate code
[LINK-2025](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2025)
[LINK-2025]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2025 | use useAdminFormStyles hook to remove duplicate code

---

src/common/components/notification/notification.module.scss
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/formSections/priceSection/PriceSection.tsx
src/domain/event/formSections/priceSection/__tests__/PriceSection.test.tsx
src/domain/event/formSections/priceSection/priceNotification/PriceNotification.tsx

Update event price section instruction texts
[LINK-1970](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1970)
[LINK-1970]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1970 | update event price section instruction texts

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/__mocks__/createEventPage.ts
src/domain/event/__mocks__/editEventPage.ts
src/domain/event/__tests__/CreateEventPage.test.tsx
src/domain/event/__tests__/validation.test.ts
src/domain/event/eventForm/EventForm.tsx
src/domain/event/eventPage.module.scss
src/domain/event/formSections/additionalInfoSection/AdditionalInfoSection.tsx
src/domain/event/formSections/additionalInfoSection/__tests__/AdditionalInfoSection.test.tsx
src/domain/event/hooks/__tests__/useEventServerErrors.test.tsx
src/domain/event/validation.ts
src/domain/registration/__mocks__/createRegistrationPage.ts
src/domain/registration/__tests__/CreateRegistrationPage.test.tsx
src/domain/registration/__tests__/validation.test.ts
src/domain/registration/formSections/attendeeCapacitySection/AttendeeCapacitySection.tsx
src/domain/registration/validation.ts

Make maximum attendee capacity field required
Update instruction texts for attendee capacities
[LINK-2069](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2069)
[LINK-2069]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2069 | make maximum attendee capacity field required

---

src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/__tests__/CreateEventPage.test.tsx
src/domain/event/__tests__/EditEventPage.test.tsx
src/domain/event/__tests__/eventTestUtils.ts
src/domain/event/__tests__/utils.test.ts
src/domain/event/createButtonPanel/__tests__/CreateButtonPanel.test.tsx
src/domain/event/eventForm/EventForm.tsx
src/domain/event/eventPage.module.scss
src/domain/event/formSections/additionalInfoSection/__tests__/AdditionalInfoSection.test.tsx
src/domain/event/formSections/classificationSection/__tests__/ClassificationSection.test.tsx
src/domain/event/formSections/descriptionSection/__tests__/DescriptionSection.test.tsx
src/domain/event/formSections/eventStateInfoSection/EventStateInfoSection.tsx
src/domain/event/formSections/externalUserContact/__tests__/ExternalUserContact.test.tsx
src/domain/event/formSections/priceSection/PriceSection.tsx
src/domain/event/formSections/priceSection/__tests__/PriceSection.test.tsx
src/domain/event/formSections/priceSection/offers/Offers.tsx
src/domain/event/formSections/priceSection/offers/offer/Offer.tsx
src/domain/event/formSections/timeSection/eventTimeTab/__tests__/EventTimeTab.test.tsx
src/domain/event/formSections/timeSection/recurringEventTab/__tests__/RecurringEventTab.test.tsx
src/domain/event/formSections/typeSection/TypeSection.tsx
src/domain/event/formSections/typeSection/publicationListLinks/PublicationListLinks.tsx
src/domain/event/utils.ts
src/domain/event/validation.ts
src/domain/events/eventsTable/eventsTableRow/EventsTableRow.tsx
src/domain/help/pages/eventsInstructionsPage/EventsInstructionsPage.tsx
src/domain/organization/organizationName/OrganizationName.tsx
src/domain/organization/utils.ts
src/domain/user/hooks/useUser.ts

Move publishing notification position
Hide type section from external user in create event form 
Hide registration price groups from external user event form
Change submit button text for external users
User publicEventSchema as base for the external user schema 
Rename "Tallenna ajankohta" button as "Tallenna ajankohta"
[LINK-2008](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2008)
[LINK-2047](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2047)
[LINK-2008]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LINK-2047]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

LINK-2008, LINK-2047 | improvements to external user event form

---

src/domain/app/i18n/constants.ts
src/domain/app/i18n/en.json
src/domain/app/i18n/fi.json
src/domain/app/i18n/sv.json
src/domain/event/__tests__/validation.test.ts
src/domain/event/validation.ts

SoMe links should not be identical.
**[LINK-2140](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2140):**
[LINK-2140]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: event form some links validation LINK-2140

---

src/domain/accessibilityStatement/AccessibilityStatement.tsx
src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap

Update accessibility statement Traficom contact info
https://helsinkisolutionoffice.atlassian.net/browse/RATY-160

chore: update traficom contact info

---

src/domain/accessibilityStatement/AccessibilityStatement.tsx
src/domain/accessibilityStatement/__tests__/AccessibilityStatement.test.tsx

**[LINK-2230](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2230):**
[LINK-2230]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update accessibility statement LINK-2230

---

e2e/tests/events.spec.ts
e2e/tests/help.spec.ts
e2e/tests/landing.spec.ts
e2e/tests/utils.ts
package.json
playwright.config.ts
yarn.lock

Upgrading Playwright to latest version and fixing accepting cookie consents.
**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX):**

fix: firefox e2e issues LINK-2190

---

.github/workflows/ci.yml
README.md
package.json
yarn.lock

Fixed some missed Node 22 upgrade updates.

fix: fixed CI and README node mentions + package.json restrictions
